### ISSUE TITLE
[Feature Request]: Updates around non-CDISC variables

### ISSUE THREAD

**Issue by harriscw** [insightsengineering/goshawk#173]
### Feature description

Goshawk requires several variables that are non-CDISC: `BASE2`,`CHG2`,`PCHG2`,`LOQFL`,`AVISITCD`.  Based on the documentation I've seen is difficult understanding 1. that these variables are required (repeated guess and check is required) 2. what these variables actually do.  This makes for a frustrating experience when trying to use these modules.  Here's some suggestions for how this could be avoided:

- State somewhere in the roxygen that these variables are required and give an explanation of what they do.
- Possibly add an `assert_that` call to check for these variables and a clear error message of how the user should follow up
- Its my impression that several of these variables are not necessary and can be set to missing if the end users wants to.  Given this, you could set these to missing by default and parameterize functions in a way where end users can supply them if they want to use them, e.g.

```
g_lineplot = function(LOQFL_var=NULL,...){

if(is.null(LOQFL_var){
...
}else{
...
}
}

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by npaszty** [comment]
@harriscw 

thanks Will. writing vignette for goshawk and teal.goshawk so that the documentation is more helpful for users and identifies the requirements/expectations.

**Comment by npaszty** [comment]
vignettes written and available.
