### ISSUE TITLE
Package `mcr` was removed from CRAN

### ISSUE THREAD

**Issue by asbates** [insightsengineering/goshawk#185]
The `mcr` package is a dependency. It was removed from CRAN today. 

https://cran.r-project.org/web/packages/mcr/index.html

**Comment by npaszty** [comment]
@asbates 
thanks Andrew.

**Comment by npaszty** [comment]
will reach out to authors - some of whom are still at Roche. helpful.

**Comment by donyunardi** [comment]
`mcr` is back in CRAN.
Closing.
