### ISSUE TITLE
[Release]: 0.1.16

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/goshawk#238]
Release package after:

- https://github.com/insightsengineering/goshawk/pull/233
- https://github.com/insightsengineering/goshawk/pull/232

**Comment by donyunardi** [comment]
@kartikeyakirar can we close this?

**Comment by npaszty** [comment]
@donyunardi @kartikeyakirar 

the vline functionlity looks like it is working again but can you please seem my comments on the [LoQ legend PR](https://github.com/insightsengineering/goshawk/pull/232). thanks!

**Comment by kartikeyakirar** [comment]
> @kartikeyakirar can we close this?
Yes

>the vline functionlity looks like it is working again but can you please seem my comments on the https://github.com/insightsengineering/goshawk/pull/232. thanks!

@npaszty I have added issue for this https://github.com/insightsengineering/goshawk/issues/241.
