### ISSUE TITLE
Treatment Variable in Plot Title

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/goshawk#248]
### Feature description

affects all plots

there is no indication of which treatment arm is selected. this should be toggled in the title as "Planned Treatment" and "Actual Treatment" per selection made in "Select Treament Variable" UI item.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
I think the only enhancement we can provide in here is the addition of the name of the variable selected in the `Select Treatment Variable`. So we can extend the plot legend with `Treatment Variable: {name}` where `{name}` is the same as provided in the data (in this case `ARM` or `ACTARM`, but in other data this can be `X` and `Y`).

**Comment by npaszty** [comment]
there are dynamic title and labeling examples in other modules so not sure what the blocker is here.
for example, units are dynamicaly added to labels/titles

![image](https://github.com/user-attachments/assets/05e9648d-cac6-4ff4-9c92-8e99d1fdd308)
![image](https://github.com/user-attachments/assets/29f6dc6c-fbe3-4e20-86cd-e00e67891243)
![image](https://github.com/user-attachments/assets/977949c1-47f0-4a95-a655-7490f88a464d)
![image](https://github.com/user-attachments/assets/18d64fb4-b1c2-4d95-b319-05d1a6263254)
![image](https://github.com/user-attachments/assets/876389a1-4eea-4738-8477-f86e6d18b892)

by grabbing these dynamic value screen shots I now see quite a few inconsistencies in plot titling and labeling which would be great if we could address in this issue too. 

- inconsistencies in including units
- inconsistency in including the analysis variable in title or not
- specifically in density dist. the title includes stating a combined treatment being included even when the combined treatment isn't included.

**Comment by npaszty** [comment]
@m7pr @donyunardi 

I'm re-thinking this and closing it. 
rationale for closing is that the Planned and Actual treatment label is already in the legend so it is already dynamically toggled.
that is good enough for now and we have other higher valule issues to focus on. 😄
