### ISSUE TITLE
Spahghetti Plot

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/goshawk#249]
### Feature description

 - [ ] appears to be the only module where the analysis variable selection is dynamically added to the plot title as well as the plot y-axis label. it is not needed in the title since it is included in the y-axis label.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
Provided a PR to fix this in here https://github.com/insightsengineering/goshawk/pull/251

**Comment by m7pr** [comment]
@npaszty I see we also add biomarker name in `g_lineplot` should we also remove there?

**Comment by npaszty** [comment]
@m7pr 

it's the analysis variable not the biomarker value. 
![image](https://github.com/user-attachments/assets/b44ea07e-1806-445f-8f92-c6c5c6952a80)

I think we should have one issue to cover all the titling and labeling inconsistencies I've seen. I kinda did that in issue #248

**Comment by m7pr** [comment]
Agree. Sorry. Just in this case, is it ok to also extend the current issue by `g_lineplot` and then let's go over a bigger overhaul with #248?

**Comment by npaszty** [comment]
@m7pr 

yes, please orgainze the issues in a manner that facilitates. just didn't want to create an issue with a large number of items. my observations discovered some title and axis label inconsistencies so perhaps those could all be addressed in one issue. thanks
